### ISSUE TITLE
Failed to cast Closure of inner step

### ISSUE THREAD

**Issue by ChriFo** [ExpediaGroup/jenkins-spock#15]
Expected Behavior
==============================

Given are the following to pipeline steps

**mayFail.groovy**
```
def call(String name, Closure body) {
  try {
    body()
  } catch(error) {
    echo "${name} crashed"
    throw error
  }
}
```

**myStep.groovy**
```
def call(String tag, Closure body) {
  mayFail('myStep') {
    echo tag
    body()
  }
}
```
and the corresponding test should run successful.
```
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

class MyStepSpec extends JenkinsPipelineSpecification {
  def myStep = null

  def setup() {
    myStep = loadPipelineScriptForTest("vars/myStep.groovy")
  }

  def "the best test ever" () {
    when:
      myStep("superstar") {
         echo "hello world"
      }
    then:
      1 * getPipelineMock("mayFail")(["myStep", _ as Closure])
  }
}
```

Actual Behavior
==============================

The following error occurred when running the test:
```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '_' with class 'org.spockframework.lang.Wildcard' to class 'groovy.lang.Closure' due to: groovy.lang.GroovyRuntimeException: failed to invokeconstructor: public groovy.lang.Closure(java.lang.Object) with arguments: [*_] reason: java.lang.InstantiationException
        at MyStepSpec.the best test ever(MyStepSpec.groovy:16)
```

Additional Information
==============================

**java -version**
```
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

**Comment by awittha** [comment]
The signature of `mayFail.call(...)` is

`public Object call(String name, Closure body)`

When setting the expectation, you're providing a `List` with types `[String, Wildcard]`.

Groovy tries hard! It sees `mayFail.call(...)` has 2 arguments, so it looks like it's trying to cast the first 2 elements of your list to those arguments.

Unfortunately, `_ as Closure` is a combination of two idioms - the wildcard `_` is a Spock idiom, while the `as Closure` is a Groovy idiom. Typecasting during the method dispatch is a purely _Groovy_ behavior, and while _Spock_ knows what to do with `_ as Closure` (**treat** the Wildcard as a Closure), _Groovy_ probably doesn't have this Spock-specific knowledge and tries to **cast** the Wildcard to a Closure.

Change the expectation: Expect two arguments instead of a List of size 2, so that Groovy doesn't have to explicitly try to cast things:

```groovy
1 * getPipelineMock("mayFail.call")("myStep", _ as Closure)
```

**Comment by ChriFo** [comment]
Perfect. Thank you!
