### ISSUE TITLE
How to mock the setting of an environment variable?

### ISSUE THREAD

**Issue by ChriFo** [ExpediaGroup/jenkins-spock#16]
I have the following step to set an environment variable:

```{groovy}
env.CUSTOMER = 'BMT' 
```
When running the step during a unit test I got the following error message (reduced):

> groovy.lang.MissingPropertyException: No such property: CUSTOMER for class: com.homeaway.devtools.jenkins.testing.PipelineVariableImpersonator
        at [...]

Please tell me how to mock that step right. 
Thank you in general for the excellent library and in advance for your help!

**Comment by awittha** [comment]
`env` is a variable that is normally created by Jenkins code during a test-run, but does not come from a plugin or step.

Your test code needs to play the role of Jenkins and create the `env` variable in your pipeline script before it tries to run it. This is best done in Spock's `setup()` method.

In the [`whole-pipeline` example project](https://github.com/homeaway/jenkins-spock/tree/master/examples/whole-pipeline), the `scm` variable is the same:

https://github.com/homeaway/jenkins-spock/blob/c1c553a56f744c53add7cee9d7844e4df347d662/examples/whole-pipeline/src/test/groovy/JenkinsfileSpec.groovy#L11-L14

In this case, since you are clearly intending to _write_ to a property of `env`, it needs an actual dummy value for the test-run, not just `null`.

A complete test-suite might look like this:

```groovy
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

public class JenkinsfileSpec extends JenkinsPipelineSpecification {
	
	def Jenkinsfile = null
	def test_env = [:]

	def setup() {
		Jenkinsfile = loadPipelineScriptForTest("/Jenkinsfile")
		Jenkinsfile.getBinding().setVariable("env", test_env)
	}
	
	def "customer is set to 'BMT'"() {
		when:
			Jenkinsfile.run()
		then:
			1 * getPipelineMock("echo")("BMT")
	}
}
```

**Comment by ShreyasSubhedar** [comment]
This is really useful
