### ISSUE TITLE
Mix Spock and JenkinsSpock

### ISSUE THREAD

**Issue by Xaseron** [ExpediaGroup/jenkins-spock#18]
I would like to mix Spock and JenkinsSpock. i have some old tests  written in Spock. My Plan is to slowly convert these to JenkinsSpock. 
Unfortunately i doesn't go well when the JenkinsSpock tests are executed before the normal Spock tests. 
It looks like the Specification class gets overridden by the JenkinsSpecification.
In my old tests i use an Expando class, which implements some pipeline steps as functions to mock the steps.
I pass this Expando as the WorkflowScript into class i wanna test. 
So the JenkinsSpock mocks stuff that should'nt be mocked and the tests are failing.

The easiest solutions would be the enforce ordering of the tests, that Spock tests are always executed before the the JenkinsSpock tests.

**Comment by awittha** [comment]
# Please Clarify

I do not understand why this

> i have some old tests written in Spock. My Plan is to slowly convert these to JenkinsSpock.

Requires this:

> I would like to mix Spock and JenkinsSpock.

Maybe because I'm not clear on what this means:

> the JenkinsSpock tests are executed before the normal Spock tests.

Is it

1. In a single `... extends JenkinsPipelineSpecification` class, you have some tests written without using `jenkins-spock` method, and some tests written using it, or
2. You have multiple `...Spec.groovy` files, some of which extend `Specification` and some of which extend `JenkinsPipelineSpecification`, and when the `JenkinsPipelineSpecification` suites run before the `Specification` suites, the `Specification` suites don't work properly?

# Alternate Design

You should be able to create a new `SomeThingSpec.groovy` file where `SomeThingSpec extends JenkinsPipelineSpecification` as an empty class, and run your old tests with no problem after adding `jenkins-spock` as a dependency.

As you replace old tests, just re-write one single test at a time in a `JenkinsPipelineSpecification` and delete the test method from its old `Specification` file.

Would that approach work?

# Possible Way to Order Tests

It's not great for unit tests to rely on some ordering relative to each other (makes running in parallel harder, and suggests that the tests aren't isolated [which is not what's going on in `jenkins-spock`, for what it's worth]). Have you looked into the [`@StepWise`](https://github.com/spockframework/spock-example/blob/master/src/test/groovy/StepwiseExtensionSpec.groovy) Spock annotation to enforce the ordering of tests?

**Comment by awittha** [comment]
@Xaseron , do you still require assistance with this issue?
