### ISSUE TITLE
Loads scripts found in src folder.

### ISSUE THREAD

**Issue by sflynn-dell** [ExpediaGroup/jenkins-spock#25]
Desired Behavior
==============================

I would like the ability to load a groovy script found under the src folder.  These files would normally be created as a new instance of the class and the functions called on that instance.  For example, I have a  file at src/my/company/devops/GitUtils.groovy that contains helper functions.  Something like:

```
def isGitRepo(gitRepoPath = "${env.WORKSPACE"}) {
    return sh("cd ${gitRepoPath} && git rev-parse --git-dir")
}

return this
```
Notice I have the sh step as well as a global variable referenced.  In a pipeline, I am able to create a new GitUtils and call isGitRepo and it works.

But currently, loading this class as a script while it exists in a package structure does not work.  If I try:
```
loadPipelineScriptForTest("src/my/company/devops/GitUtils.groovy")
```
I get a groovy.util.ResourceException, because the file does not exist at - 
<truncated path>target/classes/src/my/company/devopsGitUtils.groovy
<truncated path>src/test/resource/src/my/company/devopsGitUtils.groovy
<truncated path>src/main/resource/src/my/company/devopsGitUtils.groovy

Notice the missing forward slash between the final folder and file name.

But if I move this class to the vars folder, removing package information, I am able to test it with no issue.

Benefits
==============================

Allow all code contained in a shared library to be testable.

**Comment by sflynn-dell** [comment]
That worked perfectly.  Thank you.  Any chance of getting this documented?  Or did I miss it?

**Comment by awittha** [comment]
It's not documented. It should be. `loadPipelineScriptForTest(...)` looks in 4 places:

```groovy
GroovyScriptEngine script_engine = new GroovyScriptEngine(
			"src/main/resources${resource_path}", // if it's a main resource
			"src/test/resources${resource_path}", // if it's a test resource
			"target/classes${resource_path}", // if it's on the main classpath
			"target/test-classes${resource_path}" ) // if it's on the test classpath
```

But the documentation only mentions regular classpath "resources" (not compiled classes) so as to avoid decision paralysis for folks approaching the library _without_ a project that forces one (or more).

There should be an "advanced" section (or similar) in the documentation for "[Testing Pipeline Scripts](https://static.javadoc.io/com.homeaway.devtools.jenkins/jenkins-spock/2.0.1/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.html#testing-pipeline-scripts)" that directs users to the GroovyDoc for that method, which will explain all the places a script can possibly be located.

**Comment by awittha** [comment]
**Extra Context:**

The reason you had to use "parent directory" twice is that `loadPipelineScriptForTest(...)` does not _expect_ to be loading source code out of your `src` folder. It doesn't expect this because source code (especially w/ groovy and java) is rarely shipped - usually the bytecode is shipped.

`jenkins-spock` would prefer to load stuff that you _are_ going to ship so that the stuff-under-test will be as useful as possible. Resources are usually shipped, as are compiled classes. Technically, a `src/my/company/.../SomeThing.groovy` is probably pretty likely to be an actual Groovy **class**, not a **[Script](http://docs.groovy-lang.org/latest/html/api/groovy/lang/Script.html)**, so `loadPipelineScript(...)` for test doesn't worry too much about enabling you to load it. Classes can be compiled, and you can use regular Spock against regular Groovy classes' bytecode.

For shared libraries that don't "ship" anything, this breaks down. For shared library classes that reference pipeline steps, this also breaks down inasmuch as you don't want to test against the compiled bytecode, but want to load the class's text into the Groovy script parser that is aware of Jenkins pipeline steps. 

(If you went and updated your maven or gradle build to include the Groovy **source files** as classpath resources, `loadPipelineScriptForTest("my/company/devops/GitUtils.groovy")` would work.)

> But if I move this class to the vars folder, removing package information, I am able to test it with no issue.

Shared library `vars` are explicitly loaded by `jenkins-spock`: https://static.javadoc.io/com.homeaway.devtools.jenkins/jenkins-spock/2.0.1/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.html#getSharedLibraryVariables() - since they'll _never_ be compiled and would never be shipped (the Shared Library plugin reads 'em right out of the git repo), they get special treatment so that you don't have to use `loadPipelineScriptForTest(...)` on them.

**Comment by sflynn-dell** [comment]
Thank you for the explanation.  That all makes sense.  

For my project, I am placing code snippets, like the one I provided by way of example, in function-only groovy files that need to be instantiated.  This avoids needing a separate script for each snippet, and allows grouping of snippets in a logical way.

Because these snippets have pipeline steps and global variables, it made sense to use jenkins-spock.  I am very glad there was a way to handle how I have configured my Jenkins library.
