### ISSUE TITLE
Use of @grab in class causing errors 

### ISSUE THREAD

**Issue by werne2j** [ExpediaGroup/jenkins-spock#26]
When using `@grab` in my class files results in an error when running tests for those files.

```
[INFO] Using Groovy 2.4.11 to perform generateStubs.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.790 s
[INFO] Finished at: 2019-03-05T11:15:22-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:generateStubs (groovy) on project: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: org/apache/ivy/Ivy: org.apache.ivy.Ivy -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

@awittha any ideas on why this would be failing? When i remove all `@grab` references the tests go through. Thanks!

**Comment by awittha** [comment]
I haven't seen this error before (but I do not use `@grab` in any of my own code, so that isn't surprising).

Would you please

1. re-run with the `--errors` flag provided to Maven (so a full stack trace will be printed)
2. Share the entire build output in a gist (if possible)
3. Share a link to the source repository (if on Github.com) if possible
4. Share snippets of how your code is using `@grab`, and how your test is accessing your code?

**Comment by werne2j** [comment]
Gist with --errors flag
https://gist.github.com/werne2j/e2183fab58f10feeee5a35dbaa37b38f

Unfortunately, I can not share the repository but i can try to provide some code snippets that may help..

I have a set of utils called `Utils.groovy`, in those utils we are using `@grab` to load a dependency..
```groovy
package sample

import java.security.KeyStore
import java.security.SecureRandom
import java.security.cert.Certificate
import java.security.cert.CertificateFactory
import javax.net.ssl.SSLContext
import javax.net.ssl.TrustManagerFactory
import javax.net.ssl.X509TrustManager

@Grab(group='org.apache.httpcomponents', module='httpclient', version='4.5.7')
import org.apache.http.ssl.SSLContexts
```

In my tests, i am importing the utils class and using a global mock, to mock that class
```groovy
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification
import sample.Utils

public class Test extends JenkinsPipelineSpecification {
  def fileToTest = null
  def mockUtils = null

  def setup() {
    fileToTest = loadPipelineScriptForTest("vars/fileToTest.groovy")

    mockUtils = GroovyMock(Utils.class, global: true)
    new Utils() >> mockUtils
  }

  def "[fileToTest] will do a thing" () {
     ...
  }
}
```

Let me know, if you need more information

**Comment by werne2j** [comment]
@awittha I was wondering if you've had anytime to look at this issue? Also, if there is anymore information I could provide to help. Thanks!

**Comment by awittha** [comment]
I'm sorry, I haven't had a chance to dive into this yet.

**Comment by robnester-rh** [comment]
@awittha - Just wondering if there was any progress on this? We seem to be stuck, as we use the ```@grab``` approach frequently in our code, as it seems to be the suggested method to integrate third-party library, per the [Jenkins documentation](https://jenkins.io/doc/book/pipeline/shared-libraries/#using-third-party-libraries).

**Comment by awittha** [comment]
@robnester-rh , are you working on the same codebase as @werne2j ? If not, could you please attempt to provide the debugging information requested in https://github.com/homeaway/jenkins-spock/issues/26#issuecomment-469787181 ?

**Comment by robnester-rh** [comment]
@awittha - I am, in fact, working on the same codebase - sorry I can't offer a second data point :disappointed:

**Comment by awittha** [comment]
Here's the answer, wired up with a dummy import of `org.apache.http.ssl.SSLContexts` in the `examples/shared-library` code: https://github.com/homeaway/jenkins-spock/commit/493dade7837353a5986602e88f2b2be2f99fcefe

There's a lot going on here; here's _why_ that's the answer.

# 1. `@Grab` Uses `ivy` But It Isn't There

The `@Grab` annotation uses Apache Ivy, but Ivy isn't a hard dependency of Groovy. The "basic" setup of `jenkins-spock` doesn't tell you to explicitly add a dependency on Apache Ivy, so `@Grab` fails to even start.

> *Getting Class Not Found: org.apache.ivy.core.report.ResolveReport when using GroovyClassLoader in Java*
> -- https://stackoverflow.com/a/35830081

Adding the dependency on Apache Ivy gets us past that, but then

# 2. We Aren't Running in Groovy

Tests aren't run with Groovy; they're run with Java by the `maven-surefire-plugin`. Groovy compiles to Java bytecode, so why does that matter? Well, `@Grab`'s implementation _insists_ on having a `GroovyClassloader` available to load the classes it Grabs. This just won't be the case when unit-testing with the `maven-surefire-plugin`.

> *No suitable classloader found for grab*
> -- https://stackoverflow.com/a/26667029

Can we work around that? Thankfully, as of Groovy 2.1, we can:

# 3. Tell The Groovy Compiler to Not Grab

Luckily, the groovy compiler supports a [configuration option - `setDisabledGlobalASTTransformations(java.util.Set)`](http://docs.groovy-lang.org/latest/html/api/org/codehaus/groovy/control/CompilerConfiguration.html#setDisabledGlobalASTTransformations(java.util.Set)) to disable compiling `@Grab` annotations to bytecode that will try to fetch dependencies at runtime. Double-lucky, the [`gmavenplus-maven-plugin` supports configuring the compiler it uses](https://github.com/groovy/GMavenPlus/wiki/Examples#configuration-script).

So, we provide a `config.groovy` for the `gmavenplus-maven-plugin` to provide to our Groovy compiler, and tell it to not process `@Grab` annotations.

Finally, `@Grab` is disabled and won't try to do anything when the code runs in a Java JVM during unit tests.

_(Figured this out thanks to [Gradle, which also doesn't run with a `GroovyClassLoader` and so gets the same error](https://github.com/gradle/gradle/issues/1031))_

# 4. Dependencies Go In `pom.xml`

Without `@Grab`, how will you get your dependencies, though? With the above steps done, the tests will run and encounter `NoClassDefFound` exceptions for all the things you were trying to `@Grab` and import.

Just put 'em in the `pom.xml` as a regular dependency, maven-style. Use the `<scope>test</scope>` because _Groovy_ can compile the code without `@Grab` just fine - it's the Java JVM running tests that won't have access to the classes unless you add them to the pom.xml.

# Follow-Up

Please let me know if you're able to get tests working in this way.

**Comment by werne2j** [comment]
@awittha Thank you so much for helping out with this issue. I was able to use the answer you provided to solve my problem. Glad we could get this documented out for anyone else who may come across this issue in the future. Thanks again!

**Comment by obfischer** [comment]
Thank you for the description of the solution. It helped my to solve the same problem for my setup.
