### ISSUE TITLE
Declarative pipeline help

### ISSUE THREAD

**Issue by werne2j** [ExpediaGroup/jenkins-spock#27]
I have a declarative pipeline that i am trying to write tests for..

`vars/examplePipeline.groovy`
```
def call(settings = [:]) {
  pipeline {
    agent none
    stages {
      stage('Example') {
        agent any
        steps {
            ...
        }
      }
    }
  }
}
```
`ExamplePipelineSpec.groovy`
```
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

public class ExamplePipelineSpec extends JenkinsPipelineSpecification {
  def examplePipeline = null

  def setup() {
    examplePipeline = loadPipelineScriptForTest("vars/examplePipeline.groovy")
  }

  def "[examplePipeline] will load" () {
    when:
      examplePipeline()
    then:
      assert true
  }
}
```

I have added the `pipeline-model-definition` plugin as a dependency, which should be all i need. However when i run the test, i get this error `During a test, the pipeline step [agent] was called but there was no mock for it.`. @awittha would you have any idea why jenkins-spock would not be mocking out that step, even though it is in the plugin?

**Comment by awittha** [comment]
To write a declarative pipeline, you write _data_ that declares your pipeline. It isn't "Jenkins Pipeline Code," so `jenkins-spock` can't test it.

In `examplePipeline.groovy`,

1. `def call(...)` is a Groovy function
2. `pipeline { ...` is a Pipeline step
3. this block:
    ```
        agent none
        stages {
          stage('Example') {
            agent any
            steps {
                ...
            }
          }
        }
    ```
    is data.

`jenkins-spock` doesn't have any awareness that the `pipeline` step is special, so it tries to execute the _code_ in the body block of your pipeline step named `pipeline`. This of course fails, since it's not actual pipeline code.

Even if there was a mechanism to disable this body-block execution (there isn't (currently?)), there is also not a mechanism in jenkins-spock for parsing pipeline declarations & getting executable steps out of them.

_Further Context/Discussion:_

We would need to write code to explicitly identify the `pipeline { ...` step as special, and then hook up some declarative pipeline linting tools to validate the syntax... and after _that_, we'd also need to  hook up the declarative pipeline interpreter/engine itself in order to get executed steps out of the pipeline declaration.

I haven't looked into the declarative pipeline implementation to determine if this is currently possible. At the very least, I believe adding linting/syntax validation for the `pipeline { ...` step would be a valuable enhancement.

_Ideologically_, **you don't unit-test data**. Validate it against its schema (this would be a declarative pipeline linter / syntax validator), and then trust it. If at any point in your declarative pipeline you reference a scripted step (e.g. from a shared library, or function elsewhere in your Jenkinsfile), unit-test _that_.

**Comment by werne2j** [comment]
@awittha thank you again for the help! Your explanation explains it perfectly!

**Comment by tnguyen14** [comment]
FWIW, I do syntax linting/ validation using the Jenkins HTTP POST API https://jenkins.io/doc/book/pipeline/development/#linter

**Comment by mcascone** [comment]
Hi @awittha, i just watched your talk on jenkins-spock, and was really disappointed to learn it is not applicable to Declarative pipelines. That was then, though, and I'm wondering if any further work has been done, by anyone, on making this usable for Declarative? If not jenkins-spock, then what other options might there be? I can't find anything nearly as appetizing as this.
Certainly the linter prerequisite is now available as the pipeline-validator API/CLI and [the VSCode linter](https://github.com/janjoerke/vscode-jenkins-pipeline-linter-connector) (which uses the API, and _only_ supports Declarative).
I agree with the theoretical argument that you don't test data; would that then apply to any DSL? For example, the Chef DSL can be unit tested with their [ChefSpec](https://github.com/chefspec/chefspec) unit test harness.I don't mean to make a specious argument, I'm just wondering why the Declarative DSL seems off-limits.

**Comment by deblaci** [comment]
Hi,
Why are you using declarative pipeline? What advantages does it have?

**Comment by mcascone** [comment]
@deblaci, I'm not sure if this is the right place for a debate on Declarative vs. Scripted pipelines, but they both have their advantages and disadvantages. Scripted is arguably more powerful and flexible; anything that can be done in groovy/java, can be done in a scripted pipeline. But like Jenkins itself, sometimes its complexity and configurability are both its biggest strength and its weakness. (See also: Jira.)

In My Humble Opinion, and the impression I get from using and building pipelines constantly, the direction Jenkins is nudging us is towards Declarative. In [Jenkins' own words:](https://www.jenkins.io/doc/book/pipeline/#declarative-versus-scripted-pipeline-syntax)
>Declarative Pipeline is a more recent feature of Jenkins Pipeline which:
>- provides richer syntactical features over Scripted Pipeline syntax, and
>- is designed to make writing and reading Pipeline code easier.

Also, while I use Blue Ocean far less than expected when I first saw it, if I'm not mistaken it works far better with Declarative pipes. I could be wrong about this; if I'm not, it's another clue that Jenkins is investing and building on Declarative more than Scripted. 

Personally, while I started out writing Scripted years ago, when I came back to pipelines after a few years away from it, Declarative felt much more natural and intuitive. Yes, there are situations where I would like to have more flexibility (usually involving conditionals), but, for me, the simplicity and intuitive nature of Declarative syntax wins every time. And of course, for those situations where Declarative just won't cut it, you can always throw in a `script` block and groove away.

I could go on, and I'm sure there are any number of people ready to pounce and prove me wrong, and that'd be great! I'd honestly love to hear it! I'm just one guy on the internet, who'd really like to start unit testing his declarative Jenkins pipelines.

- As a followup, has anyone had any success with [the JenkinsPipelineUnit framework](https://github.com/jenkinsci/JenkinsPipelineUnit#declarative-pipeline)?
