### ISSUE TITLE
How to test @Library?

### ISSUE THREAD

**Issue by ghost** [ExpediaGroup/jenkins-spock#28]
Greetings!

I have a pipeline with `@Library("pipeline) _ `. If I try to test this pipeline, I get the following error: 

> unable to resolve class Library ,  unable to find class for annotation
 @ line 3, column 1.
   @Library("pipeline") _
   ^

So far I was unable to resolve this error myself, find an answer in the documentation or the other issues posted here to resolve this error.

Is @Library even supported? If yes, how do I specify the test such that the error is resolved?

Thank you in advance!

Best Regards,
Oliver

**Comment by awittha** [comment]
# `pom.xml`

`@Library(...)` comes from the [`workflow-cps-global-lib-plugin`](https://github.com/jenkinsci/workflow-cps-global-lib-plugin)  so you'll need to add a `<dependency>` block to the `pom.xml` for that plugin, so that the class for `@Library(...)` will exist:

`pom.xml`: 
```xml
<!-- '@Library()' annotation -->
<dependency>
	<groupId>org.jenkins-ci.plugins.workflow</groupId>
	<artifactId>workflow-cps-global-lib</artifactId>
	<version>2.13</version>
	<scope>test</scope>
</dependency>
```

# import

You will also need to add an `import` statement to the top of each file that uses the `@Library(...)` annotation, e.g.

`Jenkinsfile`:
```
import org.jenkinsci.plugins.workflow.libs.Library

@Library( "pipeline" ) _

...
```

In Jenkins, the `@Library` annotation is automatically available on scripts' classpath. The `jenkins-spock` extension doesn't know to do this (yet? Pull Requests welcome!).

This should be harmless to include in the `Jenkinsfile` though it will be redundant when actually run in Jenkins.

With that, the code should compile & run without error.

You will need to [`explicitlyMockPipelineStep(...)`](https://static.javadoc.io/com.homeaway.devtools.jenkins/jenkins-spock/2.0.1/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.html#explicitlyMockPipelineStep(java.lang.String,%20java.lang.String)) for any pipeline steps that come from the library. You will not be able to retrieve any Groovy _classes_ from the library unless you're compiling & distributing your library in a Maven JAR... in which case just add another `<dependency>` block.

**Comment by ghost** [comment]
> You will also need to add an import statement to the top of each file that uses the @Library(...) annotation

That was missing. Thanks a lot!
