### ISSUE TITLE
Mock (implicit-*) steps

### ISSUE THREAD

**Issue by ghost** [ExpediaGroup/jenkins-spock#29]
Greetings!

I want to test a shared library function in `/vars`. I mocked the step in a then-block:

`then:
            1 * getPipelineMock("prepare.call")(_)`

However, the invoked step is declared as implicit-expected and the mock in the then-block ignores the invoked step.

The code is from the test report:

```
1 * getPipelineMock("prepare.call")(_)   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * (implicit-expected) getPipelineMock("prepare.call").call()
```

The same issue also occured when I tried to test non-shared-library steps like jobDsl.

Explicitly mocking the step with `explicitlyMockPipelineStep("prepare.call")` did not help either.

What can I do to let the invocations match?

Kind Regards,
Oliver

**Comment by awittha** [comment]
I'm not sure exactly what your setup is - if the following suggestion doesn't work, please provide

1. layout of your files
2. actual (or sanitized, if not possible) code-under-test
3. actual (or sanitized, if not possible) test code

If you are testing a shared library, then [steps in `/vars` are already automatically mocked](https://static.javadoc.io/com.homeaway.devtools.jenkins/jenkins-spock/2.0.1/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.html#mock-shared-library-variables) (click for documentation).

See the [example shared library](https://github.com/homeaway/jenkins-spock/tree/master/examples/shared-library) and specifically its [`DefaultPipelineSpec.groovy`](https://github.com/homeaway/jenkins-spock/blob/master/examples/shared-library/test/DefaultPipelineSpec.groovy#L38) for a working example of how to expect interactions with Shared Library groovy code in the `vars/` directory of the current project.

If you're seeing an unmatched `implicit-expected` invocation, then that means that the mock was created due to your use of `getPipelineMock(...)` in an expectation, for a function name that was _not_ detected as something that should be mocked. Unmatched invocation, of course, means that your code didn't run the expected function call when it was executed.

Verify that

* you have a `vars/prepare.groovy` (exactly that name - was there a typo?)
* `vars/prepare.groovy` has a `def call(...)` function
* your test code actually runs `prepare(...)` to interact with the mock

**Comment by ghost** [comment]
Thanks for the response!

I should have been more precise: I try to test a pipeline which uses a shared library.
The pipeline under test is in `pipes/pipe.groovy` and uses `prepare()` which is implemented in `vars/prepare.groovy`. `pipes/seeded.groovy` and `vars/prepare.groovy` are in the same repo.

I verified that there is no typo, `def call (...)` is present and `prepare(...)` is run. 

The test-code:
```
def "Seeded Job Test" () {
	setup:
	    def script = loadPipelineScriptForTest("pipes/pipe.groovy")

        when:
            script.run()

        then:
            1 * getPipelineMock("node")(_)
            1 * getPipelineMock("timestamps")(_)
            1 * getPipelineMock("prepare.call")(_)
    }
```

The code under test:
```
// pipes/pipe.groovy
#!/usr/bin/env groovy
import org.jenkinsci.plugins.workflow.libs.Library

@Library("pipeline") _

node {
    ...
    timestamps {
        prepare()
        ...
    }
}
```

```
// vars/prepare.groovy
def call() {
    stage("Prepare") {
        echo "Prepare workspace"
        cleanWs()
    }
}
```

**Comment by awittha** [comment]
It sounds like the code layout should work.

What does your `pom.xml` look like? Is the [`/vars` directory a `<testResource>`](https://github.com/homeaway/jenkins-spock/blob/master/examples/shared-library/pom.xml#L277-L282) ?

**Comment by ghost** [comment]
Yes, it is. Is it ok like this?

```
// pom.xml
...
<testResource>
	<includes>
		<include>Jenkinsfile</include>
		<include>pipes/**/*.groovy</include>
		<include>vars/*.groovy</include>
	</includes>
	<directory>${project.basedir}</directory>
</testResource>
...
```

**Comment by ghost** [comment]
Greetings! Do you need some additional information?

**Comment by awittha** [comment]
What does the directory layout of your project look like? Is it possible to include the output of the `tree` command?

**Comment by ghost** [comment]
The output looks like this:

```
C:.
- .settings
- .vscode
- pipes // here go my template pipelines using the steps in vars
- resources
- src
-- main
--- java
--- resources
- test // here go my *Spec.groovy files
- vars
```

**Comment by awittha** [comment]
I have replicated the described configuration in the "issue-29" branch of this repository: https://github.com/homeaway/jenkins-spock/tree/issue-29/examples/shared-library 

It works.

Please check out that branch and try it, and if _that_ works, examine your own project for differences between how that branch is set up, and how your project is set up.

**Comment by awittha** [comment]
Aside: It looks like you're on Windows?

I wonder if there's some subtle "paths-intended-for-NIX-machines-aren't-working-properly" issue that's preventing your shared library vars from actually ending up on the classpath where they're supposed to.

If the issue-29 branch does _not_ work for you, could you share the complete output of a test-run of _your_ project with the `mvn clean verify --debug --errors` command?

**Comment by ghost** [comment]
Hey awittha, 

Your code is working on my computer.

I have seen that you used `1 * getPipelineMock("prepare.call")()` whereas I used `1 * getPipelineMock("prepare.call")(_)`. The underscore I used seemed to be the issue. The prepare call does not expect any arguments and I assumed that the underscore also covers no arguments. Therefore, the test failed as I used the wrong argument constraint. This was a misconception on my part. Now everything works as expected.

Thank you very much for your support.

Kind Regards,
Oliver
