### ISSUE TITLE
Loading class as script to test

### ISSUE THREAD

**Issue by werne2j** [ExpediaGroup/jenkins-spock#36]
I have a class that i am trying to load in and write tests for but am getting a casting error, `org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'com.example.Example@28f36e9d' with class 'com.example.Example' to class 'groovy.lang.Script'`

Example.groovy
```
package com.example

class Example implements Serializable {
    Utils utils = new Utils()

    def execute() {
        return "Has executed"
    }
}
```
This class is throwing the error above.

---------------------------------------------

However if i switch the class to something more like:
```
package com.example

def execute() {
    return "Has executed"
}

return this
```
The test does not throw the error above

-----------------------------------------------

This is how i am testing the class:

ExampleSpec.groovy
```
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

class ExampleSpec extends JenkinsPipelineSpecification {
    def  example = null

    def setup() {
        example = loadPipelineScriptForTest("../../src/com/example/Example.groovy")
    }

    def "[Example] will return a string" () {
        when:
           def string = example.execute()
        then:
           assert string == "Has executed"
    }
}

```
---------------------------------------

Would you have any ideas on this problem? Not sure if there is something about the class itself of maybe something in the `loadPipelineScriptForTest` that doesn't allow for that type of class to be loaded in. Thanks!

**Comment by awittha** [comment]
A Groovy _class_ is not a Groovy _script_ - you indeed cannot load a Groovy class with `loadPipelineScriptForTest` since it isn't a pipeline script.

Just write a normal unit test class for your Groovy script, instead:

```groovy
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

class ExampleSpec extends JenkinsPipelineSpecification {

	Example example = null

	def setup() {
		Example = new Example()
	}

	def "[Example] will return a string" () {
		when:
		   def string = example.execute()
		then:
		   assert string == "Has executed"
	}
}
```

_However_, in the provided `Example.groovy`, there are no Jenkins Pipeline steps used. If this reflects your actual code - that is to say, if you've got a plain vanilla Groovy class - you don't even need `jenkins-spock`! Just use vanilla Spock: 

```groovy
import spock.lang.Specification

class ExampleSpec extends Specification {

	Example example = null

	def setup() {
		Example = new Example()
	}

	def "[Example] will return a string" () {
		when:
		   def string = example.execute()
		then:
		   assert string == "Has executed"
	}
}
```

See the [`ExamplePipelineClassSpec`](https://github.com/homeaway/jenkins-spock/blob/issue-36/examples/shared-library/test/ExamplePipelineClassSpec.groovy) and [`ExampleVanillaClassSpec`](https://github.com/homeaway/jenkins-spock/blob/issue-36/examples/shared-library/test/ExampleVanillaClassSpec.groovy) in the [`shared-library` example on the `issue-36` branch](https://github.com/homeaway/jenkins-spock/tree/issue-36/examples/shared-library) for working examples of these two approaches.

**Comment by awittha** [comment]
Please let me know if this works for you.

**Comment by werne2j** [comment]
Ah yes, i didn't even think about loading in the Class and testing it normally without using `loadPipelineScriptForTest`. I did have pipeline steps in my actual code and the first example worked perfectly for me. Thanks for the help!
