### ISSUE TITLE
Assign value to explicitly mocked pipeline variable

### ISSUE THREAD

**Issue by werne2j** [ExpediaGroup/jenkins-spock#37]
@awittha Is it possible to assign a value to a pipeline variable that is mocked via `explicitlyMockPipelineVariable` or another way to assign a value to a pipeline variable without mocking it?

I am testing a class so it is being loaded in as a normal class and not as a script, so i don't have the ability to use `getBinding().setVariable("variable", "value")`.

```
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

class ExampleSpec extends JenkinsPipelineSpecification {
    def exampleClass

    def setup() {
        ExampleClass exampleClass = new ExampleClass()

        explicitlyMockPipelineVariable("variable")

        // Would like to set the value of "variable" 
    }

    ...
}
```

Thanks!

**Comment by awittha** [comment]
A pipeline variable mocked with `explicitlyMockPipelineVariable` is a placeholder for something that comes from a Java plugin annotated with `@GlobalVariable` - it's not literally a groovy variable (name to value pairing) that is globally-scoped. ([`PipelineVariableImpersonator` GroovyDoc](https://static.javadoc.io/com.homeaway.devtools.jenkins/jenkins-spock/2.0.1/com/homeaway/devtools/jenkins/testing/PipelineVariableImpersonator.html))

Because of this, no, you cannot assign a value to it (in a way consistent with its design), it is an object that will catch & mock method calls on it.

`getBinding().setVariable("name", "value")` is the correct idiom for setting the value of a groovy variable.

It sounds like `ExampleClass` in this case, despite being written as a Groovy class, is coded against some global state that is set up by Jenkins?

Something like

`ExampleClass.groovy`
```groovy
public class ExampleClass

public void printFoo() {
    echo "${foo}"
}
```

`Jenkinsfile`:
```groovy
def foo = "bar"
ExampleClass ex = new ExampleClass()

ex.printFoo() // expects to print "bar"
```

This might be a code smell - despite being a class, this class can't actually run as a class but must run _inside_ a correct Groovy Script.

Is this the situation?

**Comment by werne2j** [comment]
Ok, that makes sense on the `explicitlyMockPipelineVariable` was just wondering if that was an option.

Yeah that is the case. The class i have looks something like:
```groovy
package com.example

class ExampleClass {
    def execute() {
        dir(){ // Jenkins step
            echo ${WORKSPACE} // Variable set by Jenkins
        }
    }
}
```

**For reference**
What i am trying to do is pull out most of the code for my shared library into `src` and out of `vars`
so that i can have vars that are only a few lines of code and be able to get code coverage of the shared library which does not seem possible if the code is in `vars`

**Comment by awittha** [comment]
The purists would advise you to refactor your classes so that either constructors or methods take in Jenkins variables like `${WORKSPACE}` as arguments.

Then, the Jenkins pipeline script is responsible for explicitly mapping the "magic" global fields to regular method arguments and your classes don't have to be aware of any of that magic. To test that, your unit tests would just be sure to provide dummy values, e.g.

`ExampleClass.groovy`
```groovy
class ExampleClass {
    def execute(String _workspace) {
        dir(){ // Jenkins step
            echo _workspace
        }
    }
}
```

Then, when testing it, 

`ExampleClassSpec.groovy`
```groovy
import com.homeaway.devtools.jenkins.testing.JenkinsPipelineSpecification

class ExampleSpec extends JenkinsPipelineSpecification {
	def exampleClass

	def setup() {
		exampleClass = new ExampleClass()
	}
	
	def "some spec"() {
		exampleClass.execute( "some/dummy/workspace" )
	}
}
```

You could have the `vars` that stand between pipeline scripts and your classes do the translation, so that users still get a clean `justDoIt()` interface, but your Groovy classes aren't limited to running inside a Script.

If you can't do that, though, the only other way that I can think of that'll work is Groovy's Metaprogramming:

```groovy
def "forcibly adding a new instance variable" () {
	setup:
		exampleClass.metaClass.WORKSPACE="dummy-workspace"
	when:
		exampleClass.execute()
	then:
		1 * getPipelineMock("echo")("dummy-workspace")
}
```

This _does_ work, but it does it by making a new instance variable named `WORKSPACE` on the `exampleClass` object, which may break the class in other unexpected ways... I would not say that this is a very defensible testing pattern. Metaprogramming is already heavily used by `jenkins-spock` itself, and you may create unexpected interactions between your test suite and the framework. Probably not in this case, but I can't guarantee it.

You can see this (inadvisable approach) working in the [`shared-library` example on the `issue-37` branch](https://github.com/homeaway/jenkins-spock/blob/issue-37/examples/shared-library/test/ExampleClassSpec.groovy).

**Comment by werne2j** [comment]
Thank you for the response @awittha! Insightful as always. Will have to look back at the design of our shared library and decide what the best approach for us. Thanks!
