### ISSUE TITLE
How can i mock a shared library that have multiple methods

### ISSUE THREAD

**Issue by mrumeshkumar** [ExpediaGroup/jenkins-spock#40]
Desired Behavior
==============================
Not sure how to  mock and use in unit testing.

Please describe the new behavior the project should have.

Benefits
==============================
So that i can have single groovy file in vars and that one file have multiple methods.
eg
Logger.groovy

NotifyError(String)

NotifyMessage(String)

NotifySlack(MAP[] configuration)

Please list the benefits of updating the project to have the new behavior, e.g.

1. Builds more quickly
2. Enable compatibility with a new platform

**Comment by awittha** [comment]
jenkins-spock does not support mocking shared libraries. However, you can use it to _test_ a shared library, and _other_ pipeline steps - such as `echo`, `sh`, etc can be mocked.

It sounds like you're trying to _test_ a shared library. Is that right? If so, the following should help:

In Groovy, `name(...)` is implicitly dispatched to `name.call(...)`, which is why in the shared-library example,  we can use `Deployer(...)` even though `Deployer.groovy` defines a method named `call`.

https://github.com/homeaway/jenkins-spock/blob/master/examples/shared-library/test/DeployerSpec.groovy

For any other method name, just invoke it. In your case, `Logger.NotifyError(...)` & `Logger.NotifyMessage(...)` would work.

**Comment by awittha** [comment]
@mrumeshkumar , do you still require assistance?
