### ISSUE TITLE
How to mock sh(returnStatus: true, script: "")

### ISSUE THREAD

**Issue by sandeshwani** [ExpediaGroup/jenkins-spock#41]
How can I mock `int tagExist = sh(returnStatus: true, script: "git tag -l | grep -w ${tagName}\$")` ?  
**Error Message:** `myTest(MyTestSpec)  Time elapsed: 0.973 s  <<< ERROR!
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead
        at MyTestSpec.myTest `

**Comment by awittha** [comment]
`sh` was successfully mocked!

What you're asking about is _stubbing_ the mocked interaction, so that it returns a non-null value.

Spock's documentation will work just fine: http://spockframework.org/spock/docs/1.0/interaction_based_testing.html#_stubbing

The only "trick" is to remember to use `getPipelineMock("sh")` to get the mock object to stub.

In your case, probably the following:

```groovy
getPipelineMock("sh")([ returnStatus: true, script: "git tag -l | grep -w ${tagName}\$" ] ) >> 1
```

Would cause that mocked interaction to return 1 instead of `null`.

You may want to read up on _agument contstraints_ and _argument capture_ to have a smarter stubbing. With the above, if you even add a single space to the end of the `script` in your pipeline script, the test would break. This might be too strict for some situations!

1. Spock Argument Constraints: http://spockframework.org/spock/docs/1.3/interaction_based_testing.html#_argument_constraints
2. `jenkins-spock` specific notes regarding argument capture: https://static.javadoc.io/com.homeaway.devtools.jenkins/jenkins-spock/2.0.1/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.html#mock-pipeline-steps

**Comment by awittha** [comment]
@sandeshwani , do you still require assistance?

**Comment by sandeshwani** [comment]
Yup, that helped. But due to other priorities, I moved away from this work. My next goal is to have test coverage in place (OpenClover). Any suggestions? 
Thanks for all the help and I am really sorry for the delay.

**Comment by sandeshwani** [comment]
Let me know if you have any suggestions.
