### ISSUE TITLE
How to set env variables while testing a groovy class.

### ISSUE THREAD

**Issue by sandeshwani** [ExpediaGroup/jenkins-spock#43]
```
class SampleClass implements Serializable{
	private def steps
	private def readObj
	
	SampleClass(def steps){
		this.steps = steps
	}

	void sampleMethod(String path){
		if(steps.env.NODE_NAME){
			steps.println("Jenkins env.NODE_NAME is set so it is inside a node")
			readObj = readYaml(file: path)
		}
	}
}
```

This is how I am testing: 

```
class SampleTesting extends JenkinsPipelineSpecification{
	
	SampleClass obj
	
	void setup(){
     obj = new SampleClass(this)
 	}
	
	void "Testing sampleMethod"(){

		when:
		obj.sampleMethod("/tmp/xyz.yaml")

		then:
		1 * getPipelineMock("readYaml")("/tmp/xyz.yaml") >> {
			def map = [name: 'Gromit', likes: 'cheese', id: 1234] as LinkedHashMap
			return  map
		}

	}
}
```

This test will always fail as I can't find a way to set env variable. The only way avaiable is using loadPipelineScriptForTest()
```
def s = loadPipelineScriptForTest("path/to/pipelineScript")
s.getBinding().setVariable("env", [ NODE_NAME: "testNode" ])
```
but this is a groovy class and we cannot use loadPipelineScriptForTest()

Is there any way I can set env variable in such cases?

**Comment by awittha** [comment]
SampleClass expects its `steps` member variable to have a property defined named `env`.

Why not just

```groovy
void setup() {
	steps = [
		"env": [
			"NODE_NAME": "value"
		]
	]
	obj = new SampleClass( steps )
}
```

Beyond that, though, I might suggest refactoring SampleClass and/or sampleMethod so that they don't rely on the `env` that Jenkins creates. I note that `readYaml` is also a pipeline step, and so the "Groovy Class" cannot really stand on its own outside of a Jenkins pipeline.

Is it really appropriate to put that code in a standalone Groovy class? You could use a Shared Library Global Variable instead. If you did that, the existing examples for setting `env` with `loadPipelineScriptForTest(...)` would work properly.

**Comment by sandeshwani** [comment]
I agree that the groovy classes should be independent of the Jenkins pipeline step, but that will involve too much refactoring to get the test running. Current I am doing the following to get pass this issue. 

```
getPipelineMock("env.getProperty")("NODE_NAME") >> "testNode"
```
So the whole test case looks like: 
```
class SampleTesting extends JenkinsPipelineSpecification{
	
	SampleClass obj
	
	void setup(){
     obj = new SampleClass(this)
     getPipelineMock("env.getProperty")("NODE_NAME") >> "testNode"
 	}
	
	void "Testing sampleMethod"(){

		when:
		obj.sampleMethod("/tmp/xyz.yaml")

		then:
		1 * getPipelineMock("readYaml")("/tmp/xyz.yaml") >> {
			def map = [name: 'Gromit', likes: 'cheese', id: 1234] as LinkedHashMap
			return  map
		}

	}
}
```
This works :) 
Thanks for all the help. 
Share your thoughts, I will close this issue on Monday

**Comment by sandeshwani** [comment]
> SampleClass expects its `steps` member variable to have a property defined named `env`.
> 
> Why not just
> 
> ```groovy
> void setup() {
> 	steps = [
> 		"env": [
> 			"NODE_NAME": "value"
> 		]
> 	]
> 	obj = new SampleClass( steps )
> }
> ```
> 
> Beyond that, though, I might suggest refactoring SampleClass and/or sampleMethod so that they don't rely on the `env` that Jenkins creates. I note that `readYaml` is also a pipeline step, and so the "Groovy Class" cannot really stand on its own outside of a Jenkins pipeline.
> 
> Is it really appropriate to put that code in a standalone Groovy class? You could use a Shared Library Global Variable instead. If you did that, the existing examples for setting `env` with `loadPipelineScriptForTest(...)` would work properly.

If I do
```
steps = [
		"env": [
			"NODE_NAME": "value"
		]
	]
	obj = new SampleClass( steps )
```
this won't work 
```
1 * getPipelineMock("readYaml")("/tmp/xyz.yaml") >> {
			def map = [name: 'Gromit', likes: 'cheese', id: 1234] as LinkedHashMap
			return  map
		}
```
I need to pass `this` while creating object
`obj = new SampleClass(this)`
Everything falls back to how the groovy class is designed.

**Comment by awittha** [comment]
Thank you for following up!

In Jenkins, `this` is probably the Pipeline script execution.
In `jenkins-spock`, `this` is probably the `JenkinsPipelineSpecification` test suite.

In actual use, you're passing the `this` into your Groovy class so that the class can call pipeline steps, right? This happens to work because even though the JenkinsPipelineSpecification isn't a running Jenkins Pipeline script, it catches the attempts to call pipeline steps (like `steps.println`) and forwards them to the correct mocks.

It might be more ideologically correct to [prepare additional objects](https://static.javadoc.io/com.homeaway.devtools.jenkins/jenkins-spock/2.0.1/com/homeaway/devtools/jenkins/testing/JenkinsPipelineSpecification.html#preparing-additional-objects) - in this case, a dummy object could stand in for the Jenkins Pipeline. Something like:

```groovy
def setup() {
    def mockPipeline = new Object()
    addPipelineMocksToObjects( mockPipeline )
    obj = new SampleClass( mockPipeline )
}
```

The end result should be identical, but you're explicitly creating a dummy/stand-in for the running Jenkins Pipeline script.

**I'm not really sure what 'best practice' would really be here, though:** no one's asked this specific question about this specific situation before.

For the future, I'd recommend putting Pipeline of code in a shared library Global Variable, and keeping Groovy classes "pure groovy" without any Jenkins-specific dependencies.

**Comment by sandeshwani** [comment]
Thanks for the quick response. Yup, it works the same way. I will go ahead with the one you suggested.
