### ISSUE TITLE
Examples should always use latest released version of jenkins-spock

### ISSUE THREAD

**Issue by rnc** [ExpediaGroup/jenkins-spock#63]
Issue
=====

Examples are using an old version of jenkins spock

Expected Behavior
==============================

Examples should use current version of jenkins spock (and be automatically updated on release)

**Comment by awittha** [comment]
Fixed in #74 ; you can see the commit that will now happen automatically during future releases here: https://github.com/ExpediaGroup/jenkins-spock/commit/ae13262cd2ed3515bca8a1a9247ef39270e0cbd6

The only hiccup is that due to the lag time in artifacts becoming available in maven-central, the "examples" may be broken for a few hours after each release... :(

e.g. https://github.com/ExpediaGroup/jenkins-spock/runs/721576010?check_suite_focus=true
